#!/bin/sh
set -eu

usage() {
cat <<EOF
Usage:
 depthchargectl [options]

Manage ChromeOS kernel partitions.

Options:
 -h, --help                 Show this help message.
 -v, --verbose              Print more detailed output.
EOF
}

. "lib/msg.sh"


# Parse options and arguments
# ---------------------------

# Check verbose options before printing anything.
for arg in "$@"; do
    case "${arg:-}" in
        -v|--verbose) VERBOSE=yes ;;
        --) break ;;
    esac
done

while [ "$#" -gt 0 ]; do
    case "$1" in
        # Options:
        -h|--help)          usage;                      exit 0 ;;
        -v|--verbose)       VERBOSE=yes;                shift 1 ;;

        # End of options.
        --) shift; break ;;
        -*) usage_error "Option '$1' not understood." ;;
    esac
done


# Set argument defaults
# ---------------------

# Verbosity options.
: "${VERBOSE:=no}"
: "${QUIET:=no}"
: "${SILENT:=no}"

readonly VERBOSE QUIET SILENT
