#!/bin/sh
set -e

usage() {
cat <<EOF
Usage: depthcharge-set-good [options]

Options:
 -h, --help              Show this help message.
 -u, --partuuid UUID     Use this PARTUUID to find a partition, instead
                         of searching kern_guid=UUID in kernel cmdline.
EOF
}

# Prefer to use files from the repository.
if [ -n "$CHECKOUT" ]; then
    : "${FUNCTIONS:=${CHECKOUT}/functions}"
fi

# Things we might want to override when testing.
: "${PROC_CMDLINE:=/proc/cmdline}"

# Distro-specific paths for installed files.
: "${FUNCTIONS:=/usr/share/depthcharge-support/functions}"

# Import common functions.
. "$FUNCTIONS"

parse_args() {
    while [ "$#" -gt 0 ]; do
        case "$1" in
            -h|--help)
                print_help
                exit 0
                ;;
            -v|--verbose)
                VERBOSE=yes
                shift
                ;;
            -u|--partuuid)
                PARTUUID="$2"
                shift 2
                ;;
            -*)
                usage_error "Option '$1' not understood."
                ;;
            *)
                usage_error "Argument '$1' not understood."
                ;;
        esac
    done

    if [ -z "$PARTUUID" ]; then
        PARTUUID="$(get_kern_guid)" \
            || error "No PARTUUID specified and none can be found" \
            "from the kernel command-line parameters."
    fi
}

main() {
    parse_args "$@"

    if [ "$VERBOSE" != yes ]; then
        exec >/dev/null
    fi

    partdev="$(cgpt_ find -1 -u "$PARTUUID" 2>/dev/null)" \
        || error "No partition with PARTUUID='$PARTUUID' found."
    disk="$(disk_from_partdev "$partdev")"
    partno="$(partno_from_partdev "$partdev")"

    typeguid="$(cgpt_ show -i "$partno" -t "$disk")"
    if [ "$typeguid" != "FE3A2A5D-4F32-41A7-B725-ACCC3285A309" ]; then
        error "Partition '$partdev' is not a ChromeOS kernel partition."
    fi

    cgpt_ add -i "$partno" -T 1 -S 1 "$disk" \
        || error "Failed to set partition '$target' as successful."
    cgpt_ prioritize -i "$partno" "$disk" \
        || error "Failed to prioritize partition '$target'."
    cgpt_ show -i "$partno" "$disk"
}

main "$@"
