#!/bin/sh

set -e

# Disable if our package is not installed.
if ! command -v depthchargectl >/dev/null 2>&1; then
    exit 0
fi

# Don't run if update-initramfs is going to generate an initramfs, as
# we will run after that anyway.
if [ -f /etc/kernel/postinst.d/initramfs-tools ] \
    && [ -x /usr/sbin/update-initramfs ] \
    && [ "$INITRD" != 'no' ]
then
    exit 0
fi

kversion="$1"
vmlinuz="${2:-/boot/vmlinuz-$kversion}"

set -- $DEB_MAINT_PARAMS
action="$1"
version="$2"

# Run only once at the end.
case "$action" in
    "configure"|"'configure'"|'')
        count="$(depthchargectl partitions -n -o DEVICE 2>/dev/null | wc -l)"
        if [ "$count" -gt 1 ]; then
            exec depthchargectl write "$kversion"
        else
            exec depthchargectl write --allow-current "$kversion"
        fi
        ;;
esac
