#!/bin/sh

set -e

# Disable if our package is not installed.
if ! command -v depthchargectl >/dev/null 2>&1; then
    exit 0
fi

kversion="$1"
vmlinuz="${2:-/boot/vmlinuz-$kversion}"

set -- $DEB_MAINT_PARAMS
action="$1"
version="$2"

# Run only once at the end.
case "$action" in
  "configure"|"'configure'"|'')
    exec depthchargectl write "$kversion"
  ;;
esac
