#!/bin/sh

set -e

# Disable if our package is not installed.
if ! command -v depthchargectl >/dev/null 2>&1; then
    exit 0
fi

kversion="$1"
initrd="$2"

count="$(depthchargectl partitions -n -o DEVICE 2>/dev/null | wc -l)"
if [ "$count" -gt 1 ]; then
    exec depthchargectl write "$kversion"
else
    exec depthchargectl write --allow-current "$kversion"
fi
